version: "3.8"
services:
  db:
    hostname: ${POSTGIS_SERVER}
    image: postgis/postgis:${POSTGIS_IMG_TAG:-latest}
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGIS_USER}
      POSTGRES_PASSWORD: ${POSTGIS_PASS}
      POSTGRES_DB: ${POSTGIS_DBNAME}
    ports:
      - ${POSTGIS_PORT}:5432
    volumes:
      - postgis-data:/var/lib/postgresql/data
    profiles:
      - dev
      - pgadmin
  pgadmin:
    hostname: ${PGADMIN_SERVER}
    image: dpage/pgadmin4:${PGADMIN_IMG_TAG:-latest}
    depends_on:
      - db
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USERNAME}@${PGADMIN_DOMAIN}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_SERVER_JSON_FILE: /servers.json
    ports:
      - ${PGADMIN_HTTP_PORT}:80
    volumes:
      - ./pgadmin_conf:/var/lib/pgadmin
      - ./servers.json:/servers.json:ro
    profiles:
      - pgadmin

volumes:
  postgis-data:
    name: ${COMPOSE_PROJECT_NAME:-dev_docker_postgis}-${POSTGIS_SERVER}-postgis-data
